apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: portal-dev

namespace: staging

resources:
  - ../../base

labels:
  - pairs:
      app.kubernetes.io/environment: dev
    includeSelectors: false

patches:
  - path: deployment-patch.yaml
  - path: configmap-patch.yaml
  - path: route-patch.yaml

images:
  - name: portal
    newName: quay.io/rhopl/portal
    newTag: dev
