name: "CI: Main Branch"

on:
  push:
    branches: [main]

concurrency:
  group: main-${{ github.sha }}
  cancel-in-progress: true

jobs:
  ci:
    name: Validate
    uses: ./.github/workflows/ci.yml
